from fabric.api import *

def run():
	local('python manage.py runserver')

def c():
	local('git add --all')
	local('git commit -m "automated commit generated by fabfile"')

def push_master():
	local('git push origin master')
